#Include %A_ScriptDir%\src\shortcuts\vim\copy-paste-cut.ahk
#Include %A_ScriptDir%\src\shortcuts\vim\delete.ahk
#Include %A_ScriptDir%\src\shortcuts\vim\lines.ahk
#Include %A_ScriptDir%\src\shortcuts\vim\start-end-of-line.ahk
#Include %A_ScriptDir%\src\shortcuts\vim\undo-redo.ahk
#Include %A_ScriptDir%\src\shortcuts\vim\word-right-left.ahk
#Include %A_ScriptDir%\src\shortcuts\vim\arrows.ahk
#Include %A_ScriptDir%\src\shortcuts\vim\navigation.ahk
#Include %A_ScriptDir%\src\shortcuts\vim\numbers-first.ahk
#Include %A_ScriptDir%\src\shortcuts\vim\indent.ahk
#Include %A_ScriptDir%\src\shortcuts\vim\case.ahk
#Include %A_ScriptDir%\src\shortcuts\vim\char-movement.ahk
#Include %A_ScriptDir%\src\shortcuts\vim\repeat.ahk
